### PR TITLE
Fully Support Styles

### PR DESCRIPTION
**Pull request by rickychilcott**
Implement creating, removing, and editing existing document styles.

It's a massive PR. Sorry.

But it works and it's cool. So it's got that going for it.

### CODE REVIEW

**Comment by satoryu** [comment]
@rickychilcott, thank you for opening this pull request!
As you pointed out, support for Ruby 2.6 should be dropped. I will take care of it, so please disregard the failure on Ruby 2.6 at the moment.

**Comment by satoryu** [comment]
FYI: #146

**Comment by rickychilcott** [comment]
Cool, thanks! I merged in master and added a bit more documentation!

**Comment by rickychilcott** [comment]
Hey @satoryu! We've now shipped a feature in our application using my fork, and it's working like a charm. Are you willing to review this to see if we could consider getting this merged in?

**Pull request merged**
