### PR TITLE
Support color and strike tag in to_html

### PR DESCRIPTION
**Pull request by supraja-trd**
To Fix : https://github.com/ruby-docx/docx/issues/126

1. Supports color tag in style
2. Supports < s > tag

### CODE REVIEW

**Comment by supraja-trd** [comment]
Hi @satoryu  , Kindly review this PR . I do not have write access for the repo. Let me know how to proceed further to have my code merged to repo .

**Comment by supraja-trd** [comment]
Hi @satoryu  , Are we good to merge this PR ? I don't have write access for this repository . Could you let me know how to proceed ?

**Comment by manovasanth1227** [comment]
Hi @satoryu , can you pls review this PR ?

**Review by satoryu — APPROVED** [review]
@supraja-trd thank you for your pull request and your effort!

**Pull request merged**
